# 说明:
# 1、未注释的都是必填项
# 2、英文 : 后要空一格, domains 和 tips 里的 - 代表分组, 不可省略

domain: mibiao.vercel.app
title: 萌客米表
#donate: 可选, 打赏链接, 完整的可访问链接

# 对应四种颜色, 尽量选择 #123456 这种样式
color:
  default: red
  reserved: orange
  onsale: green
  sold: gray

# true: 标签模式, false: 文本模式
badge: false

# 公告
# url: 可选, title 超链接地址
# price: 可选，自定义内容，不一定是数字
tips:
  - title: 公告一
    description: 公告内容
  - title: 公告二
    description: 公告内容
  - title: 公告三
    description: 公告内容

# 域名列表
# url 可选, domain 超链接地址, 比如议价的话可跳转到自定义的报价页面
# price 可选，但建议都写上，自定义内容，不一定是数字
# 非卖品
reserved-domains:
  - domain: a.com
    description: 描述内容
    price: 非卖品
  - domain: b.com
    description: 描述内容
    price: 非卖品
  - domain: c.com
    description: 描述内容
    price: 非卖品
# 出售中
onsale-domains:
  - domain: a.com
    description: 描述内容
    price: $888
  - domain: b.com
    description: 描述内容
    price: 议价
  - domain: c.com
    description: 描述内容
    price: ￥666
# 已售出
sold-domains:
  - domain: a.com
    description: 描述内容
    price: 已出售
  - domain: b.com
    description: 描述内容
    price: 已出售
  - domain: c.com
    description: 描述内容
    price: 已出售

# 联系方式
# url 可选, 超链接地址
contacts:
  - type: QQ
    text: 88888888
  - type: Email
    text: xxx@xxx.com
    url: mailto:xxx@xxx.com
  - type: 微信
    text: wx88888888

# 米表联盟
links:
  - url: https://midian.vercel.app
    description: 萌客米表
